---
title: "ENV 872L Final Project"
author: "Aadya Shukla, Humayra Rahman"
date: "`r Sys.Date()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## INSTRUCTIONS

```{r}
#1 text each other before and after coding from our ends bc two of us can't work simultaneously
#2 pull before working
# push after working
# make the commit comments as detailed as possible bc grading will depend on that
```

## What to focus on/ DELETE FOR FINAL OUTPUT

```{r}
# Limiting data from January 1st, 2003 to December 31st, 2023 because we don't have full year's data for 2000 and 2024 for Delhi, nice to see a 20 year change
# Filter for columns (6): Location, Date/Time (in ymd format), O3, PM 2.5, PM 10, AQI
# Column names: Location, Date, O3, PM2.5, PM10, AQI
# Might need extra columns for Month and Year separately BUT AFTER INITIAL WRANGLING
```


## INITIAL DATA WRANGLING

```{r Loading packages, checking working directory}

library(dplyr); library(lubridate); library(tidyverse);
library(here); library(zoo); library(trend);
library(Kendall); library(tseries); library(ggplot2)

here()

```

```{r Delhi Dataset}

Delhi_dataset_raw <- read.csv(here(
  "DelhiDataset/delhi_air_quality_feature_store_processed.csv"),
  stringsAsFactors = TRUE)

Delhi_dataset_summarized <- Delhi_dataset_raw %>% 
  select(city, event_timestamp, pm25, pm10, o3, aqi) %>% 
  mutate(event_timestamp = ymd_hms(event_timestamp)) %>% 
  filter(event_timestamp >= ymd("2003-01-01") &
    event_timestamp <= ymd("2023-12-31")) %>% 
  mutate(month = month(event_timestamp),
         year = year(event_timestamp)) %>% 
  group_by(month, year) %>% 
  summarize(
    PM2.5 = mean(pm25, na.rm = TRUE),
    PM10 = mean(pm10, na.rm = TRUE),
    O3 = mean(o3, na.rm = TRUE),
    AQI = mean(aqi, na.rm = TRUE)
  ) %>% 
  mutate(Location = "Delhi")

write.csv(Delhi_dataset_summarized, 
          here("processed/delhi_final_processed.csv"), row.names = FALSE)
  
```

```{r Dhaka Dataset}
#reading csv file
BD_dataset_raw <- read.csv(here("AQI Bangladesh.csv"),
        stringsAsFactors = TRUE)

#filtering for Dhaka only
dhaka_dataset_raw <- BD_dataset_raw %>%
  filter(city_name == "Dhaka")

view(dhaka_dataset_raw)

#filtered for date,location,pm2.5,pm10,aqi,o3
dhaka_air <- dhaka_dataset_raw %>%
  mutate(datetime = ymd_hm(datetime)) %>%
  filter(city_name == "Dhaka") %>%
  select(city_name, datetime, ozone, pm2_5, pm10, aqi) %>%
  rename(
    Location  = city_name,
    Date = datetime,
    O3        = ozone,
    PM2.5     = pm2_5,
    PM10      = pm10,
    AQI       = aqi
  ) 

# Filter date range
dhaka_air <- dhaka_air %>%
  filter(Date >= as.Date("2003-01-01") & Date <= as.Date("2023-12-31"))

dhaka_dataset_summarized <- dhaka_air %>%
  mutate(month = month(Date),
         year  = year(Date)) %>%
  group_by(month, year) %>%
  summarize(
    PM2.5 = mean(PM2.5, na.rm = TRUE),
    PM10  = mean(PM10,  na.rm = TRUE),
    O3    = mean(O3,    na.rm = TRUE),
    AQI   = mean(AQI,   na.rm = TRUE)
  ) %>%
  mutate(Location = "Dhaka")

view(dhaka_dataset_summarized)

write.csv(dhaka_dataset_summarized, 
          here("processed/dhaka_final_processed.csv"), row.names = FALSE)

```

```{r Combining Datasets Into a New Dataframe}
#reading both datasets
dhaka_final_processed <- read.csv(here("processed/dhaka_final_processed.csv"))
delhi_final_processed <- read.csv(here("processed/delhi_final_processed.csv"))

#combining into one dataframe
combined_dataset <- rbind(dhaka_final_processed, delhi_final_processed)

combined_dataset <- mutate(combined_dataset,
                           first.month = make_date(year, month, 1))

#checking for missing data
colSums(is.na(combined_dataset))

```

## TIME SERIES ANALYSES

```{r Plotting Initial Data}
#AQI
ggplot(combined_dataset, aes(y = AQI, x = first.month, colour = Location)) + 
  geom_line() +
  scale_x_date(date_breaks = "10 years", date_labels = "%Y")
  geom_smooth(method = lm) 
  
#PM2.5
  ggplot(combined_dataset, aes(y = PM2.5, x = first.month, colour = Location)) + 
  geom_line() +
  scale_x_date(date_breaks = "10 years", date_labels = "%Y")
  geom_smooth(method = lm) 
  
#PM10
  ggplot(combined_dataset, aes(y = PM10, x = first.month, colour = Location)) + 
  geom_line() +
  scale_x_date(date_breaks = "10 years", date_labels = "%Y")
  geom_smooth(method = lm) 
  
#O3
  ggplot(combined_dataset, aes(y = O3, x = first.month, colour = Location)) + 
  geom_line() +
  scale_x_date(date_breaks = "10 years", date_labels = "%Y")
  geom_smooth(method = lm) 
  
```

```{r Creating time series objects}
# Monthly AQI for Delhi
Delhi.AQI.monthly.ts <- ts(delhi_final_processed$AQI,
                           start = c(2003,1), frequency = 12)
Delhi.AQI.monthly.decomposed <- stl(Delhi.AQI.monthly.ts,
                                    s.window = "periodic")
plot(Delhi.AQI.monthly.decomposed)


# Monthly Ozone for Delhi
Delhi.Ozone.monthly.ts <- ts(delhi_final_processed$O3,
                             start = c(2003,1), frequency = 12)
Delhi.Ozone.monthly.decomposed <- stl(Delhi.Ozone.monthly.ts,
                                    s.window = "periodic")
plot(Delhi.Ozone.monthly.decomposed)


# Monthly PM2.5 for Delhi
Delhi.PM2.5.monthly.ts <- ts(delhi_final_processed$PM2.5,
                             start = c(2003,1), frequency = 12)
Delhi.PM2.5.monthly.decomposed <- stl(Delhi.PM2.5.monthly.ts,
                                    s.window = "periodic")
plot(Delhi.PM2.5.monthly.decomposed)


# Monthly PM10 for Delhi
Delhi.PM10.monthly.ts <- ts(delhi_final_processed$PM10,
                            start = c(2003,1), frequency = 12)
Delhi.PM10.monthly.decomposed <- stl(Delhi.PM10.monthly.ts,
                                    s.window = "periodic")
plot(Delhi.PM10.monthly.decomposed)



# Monthly AQI for Dhaka
Dhaka.AQI.monthly.ts <- ts(dhaka_final_processed$AQI,
                           start = c(2003,1), frequency = 12)
Dhaka.AQI.monthly.decomposed <- stl(Dhaka.AQI.monthly.ts,
                                    s.window = "periodic")
plot(Dhaka.AQI.monthly.decomposed)


# Monthly Ozone for Dhaka
Dhaka.Ozone.monthly.ts <- ts(dhaka_final_processed$O3,
                             start = c(2003,1), frequency = 12)
Dhaka.Ozone.monthly.decomposed <- stl(Dhaka.Ozone.monthly.ts,
                                    s.window = "periodic")
plot(Dhaka.Ozone.monthly.decomposed)


# Monthly PM2.5 for Dhaka
Dhaka.PM2.5.monthly.ts <- ts(dhaka_final_processed$PM2.5,
                             start = c(2003,1), frequency = 12)
Dhaka.PM2.5.monthly.decomposed <- stl(Dhaka.PM2.5.monthly.ts,
                                    s.window = "periodic")
plot(Dhaka.PM2.5.monthly.decomposed)


# Monthly PM10 for Dhaka
Dhaka.PM10.monthly.ts <- ts(dhaka_final_processed$PM10,
                            start = c(2003,1), frequency = 12)
Dhaka.PM10.monthly.decomposed <- stl(Dhaka.PM10.monthly.ts,
                                    s.window = "periodic")
plot(Dhaka.PM10.monthly.decomposed)

```

```{r Mann-Kendall Tests}


# Seasonal Mann-Kendall Dhaka

# Dhaka AQI
Dhaka.AQI.monthly.trend <- trend::smk.test(Dhaka.AQI.monthly.ts)
Dhaka.AQI.monthly.trend
summary(Dhaka.AQI.monthly.trend)
# Dhaka AQI not significant (p = 0.0768)


# Dhaka PM2.5
Dhaka.PM2.5.monthly.trend <- trend::smk.test(Dhaka.PM2.5.monthly.ts)
Dhaka.PM2.5.monthly.trend
summary(Dhaka.PM2.5.monthly.trend)
# Dhaka PM2.5 not significant (p = 0.0768)

# Dhaka PM10
Dhaka.PM10.monthly.trend <- trend::smk.test(Dhaka.PM10.monthly.ts)
Dhaka.PM10.monthly.trend
summary(Dhaka.PM10.monthly.trend)
# Dhaka PM2.5 not significant (p = 0.1068)

# Dhaka O3
Dhaka.Ozone.monthly.trend <- trend::smk.test(Dhaka.Ozone.monthly.ts)
Dhaka.Ozone.monthly.trend
summary(Dhaka.Ozone.monthly.trend)
# Dhaka ozone (O3) is significant (1.432e-06)

# Seasonal Mann-Kendall Delhi

# Delhi AQI
Delhi.AQI.monthly.trend <- trend::smk.test(Delhi.AQI.monthly.ts)
Delhi.AQI.monthly.trend
summary(Delhi.AQI.monthly.trend)
# Delhi AQI not significant (0.3226)

# Delhi PM2.5
Delhi.PM2.5.monthly.trend <- trend::smk.test(Delhi.PM2.5.monthly.ts)
Delhi.PM2.5.monthly.trend
summary(Delhi.PM2.5.monthly.trend)
# Delhi AQI not significant (0.08624)

# Delhi PM10
Delhi.PM10.monthly.trend <- trend::smk.test(Delhi.PM10.monthly.ts)
Delhi.PM10.monthly.trend
summary(Delhi.PM10.monthly.trend)
# Delhi PM10 not significant (0.4257)

# Delhi O3
Delhi.Ozone.monthly.trend <- trend::smk.test(Delhi.Ozone.monthly.ts)
Delhi.Ozone.monthly.trend
summary(Delhi.Ozone.monthly.trend)
# Delhi ozone (O3) not significant (0.3098)


# Non-Seasonal Mann-Kendall Dhaka

# Dhaka AQI
Dhaka.monthly.AQI.nonseasonal <- Dhaka.AQI.monthly.ts - 
  Dhaka.AQI.monthly.decomposed$time.series[,1]

Dhaka.nonseasonal.AQI.trend <- Kendall::MannKendall(
  Dhaka.monthly.AQI.nonseasonal)
Dhaka.nonseasonal.AQI.trend
summary(Dhaka.nonseasonal.AQI.trend)

# Dhaka PM2.5
Dhaka.monthly.PM2.5.nonseasonal <- Dhaka.PM2.5.monthly.ts - 
  Dhaka.PM2.5.monthly.decomposed$time.series[,1]

Dhaka.nonseasonal.PM2.5.trend <- Kendall::MannKendall(
  Dhaka.monthly.PM2.5.nonseasonal)
Dhaka.nonseasonal.PM2.5.trend
summary(Dhaka.nonseasonal.PM2.5.trend)

# Dhaka PM10
Dhaka.monthly.PM10.nonseasonal <- Dhaka.PM10.monthly.ts - 
  Dhaka.PM10.monthly.decomposed$time.series[,1]

Dhaka.nonseasonal.PM10.trend <- Kendall::MannKendall(
  Dhaka.monthly.PM10.nonseasonal)
Dhaka.nonseasonal.PM10.trend
summary(Dhaka.nonseasonal.PM10.trend)

# Dhaka O3
Dhaka.monthly.Ozone.nonseasonal <- Dhaka.Ozone.monthly.ts - 
  Dhaka.Ozone.monthly.decomposed$time.series[,1]

Dhaka.nonseasonal.Ozone.trend <- Kendall::MannKendall(
  Dhaka.monthly.Ozone.nonseasonal)
Dhaka.nonseasonal.Ozone.trend
summary(Dhaka.nonseasonal.Ozone.trend)

# Non-Seasonal Mann-Kendall Delhi

# Delhi AQI
Delhi.monthly.AQI.nonseasonal <- Delhi.AQI.monthly.ts - 
  Delhi.AQI.monthly.decomposed$time.series[,1]

Delhi.nonseasonal.AQI.trend <- Kendall::MannKendall(
  Delhi.monthly.AQI.nonseasonal)
Delhi.nonseasonal.AQI.trend
summary(Delhi.nonseasonal.AQI.trend)

# Delhi PM2.5
Delhi.monthly.PM2.5.nonseasonal <- Delhi.PM2.5.monthly.ts - 
  Delhi.PM2.5.monthly.decomposed$time.series[,1]

Delhi.nonseasonal.PM2.5.trend <- Kendall::MannKendall(
  Delhi.monthly.PM2.5.nonseasonal)
Delhi.nonseasonal.PM2.5.trend
summary(Delhi.nonseasonal.PM2.5.trend)

# Delhi PM10
Delhi.monthly.PM10.nonseasonal <- Delhi.PM10.monthly.ts - 
  Delhi.PM10.monthly.decomposed$time.series[,1]

Delhi.nonseasonal.PM10.trend <- Kendall::MannKendall(
  Delhi.monthly.PM10.nonseasonal)
Delhi.nonseasonal.PM10.trend
summary(Delhi.nonseasonal.PM10.trend)

# Delhi O3
Delhi.monthly.Ozone.nonseasonal <- Delhi.Ozone.monthly.ts - 
  Delhi.Ozone.monthly.decomposed$time.series[,1]

Delhi.nonseasonal.Ozone.trend <- Kendall::MannKendall(
  Delhi.monthly.Ozone.nonseasonal)
Delhi.nonseasonal.Ozone.trend
summary(Delhi.nonseasonal.Ozone.trend)



#two-sample t test

# AQI
t.test(AQI ~ Location, data = combined_dataset)

# PM2.5
t.test(PM2.5 ~ Location, data = combined_dataset)

# PM10
t.test(PM10 ~ Location, data = combined_dataset)

# O3
t.test(O3 ~ Location, data = combined_dataset)


#Linear Regression

# AQI
AQI.model <- lm(AQI ~ first.month * Location, data = combined_dataset)
summary(AQI.model)

# PM2.5
PM2.5.model <- lm(PM2.5 ~ first.month * Location, data = combined_dataset)
summary(PM2.5.model)

# PM10
PM10.model <- lm(PM10 ~ first.month * Location, data = combined_dataset)
summary(PM10.model)


# O3
O3.model <- lm(O3 ~ first.month * Location, data = combined_dataset)
summary(O3.model)
```

